### ISSUE TITLE
Handling of ties (bt) does not work : Log probability evaluates to log(0), i.e. negative infinity.

### ISSUE THREAD

**Issue by benjaminguinaudeau** [davidissamattos/bpcs#8]
Hi, 

Thanks a lot for the package! It is really handy to use and I could easily test many different model specifications.

```
dt <- dplyr::bind_rows(
  tennis_agresti, 
  tibble::tibble(player0 = "Seles", player1 = "Graf", y = 2, id = 47)
)

m1 <- bpc(data = dt,
          player0 = 'player0',
          player1 = 'player1',
          result_column = 'y',
          model_type = 'bt',
          solve_ties = 'random',
          show_chain_messages = T)
```
I obtain the following error.

```
Chain 2 Rejecting initial value:
Chain 2   Log probability evaluates to log(0), i.e. negative infinity.
Chain 2   Stan can't start sampling from this initial value.
```

The same error happens, when I use `remove` instead of random. 

Manually removing the ties solves the issue though. Still, I thought it could be usefull to report the bug.

**Comment by davidissamattos** [comment]
I am happy you find the package useful. I will double-check this issue in the next couple of days 

Update: I have fixed this issue for version 1.2.2 (minor adjustments might be necessary if it doesn't pass the R-CMD-CHECK for all platforms)
The solve ties option was only working when we had the scores and we computed who won. Now it works when ties are provided directly in the results column. Your example was also added to the test cases in the bt model.

Thanks!
David
